spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    hikari:
      maximum-pool-size: 10

#    type: org.springframework.jdbc.datasource.SimpleDriverDataSource # отключить ConnectionPool
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
logging:
  charset:
    console: utf-8